# Author: Daniel Sapojnikov 2023.
# config.toml provides configurations for WAF deployment and capabilities.

### Network Configurations

[WebServer]
ip = "127.0.0.1"
port = 50000

[Proxy]
ip = "0.0.0.0"
port = 8080

[Admin]
ip = "127.0.0.1"
port = 60000

### Further sections are related to WAF features.

[ACL]
api = "https://check.torproject.org/exit-addresses"
backup = "C:\\coding\\NetGuard\\src\\proxy_network\\TorExitNodes.txt"
interval = 1800 # 30 minutes

[Banning]
threshold = 3
factor = 3600 # 1 hour.

[GeoIP]
banned_countries = ["Iran", "North Korea", "Palestine", "Syria", "Lebanon"]

[Timezone]
time_zone = "Asia/Jerusalem"

### Further sections are related to security page information.

[SecurityPage]

# General attack info.
attack_header = "Wrongful behavior detected."
attack_additional_info = ["Your activity log was sent to our administration team and is investigated."]

# Info regarding banned software.
anonymity_header = "We have detected usage of anonymization software."
anonymity_additional_info = ["We suggest you try to connect to our services without identifying with anonymization products."]

# Info regarding banned geopraphic locations.
geo_header = "We have detected illegal activity based on your geographic location."
geo_additional_info = ["We suggest you try to connect to our services without identifying with anonymization products."]

# For both geolocation and banned software.
dirty_header = "Anonymization software and a banned geolocation have been detected."
dirty_additional_info = ["You are seeing this page because we have found your location to be untrusted",
                         "additionaly, we found anonymization attempt via anonymization software."]
