# Author: Daniel Sapojnikov 2023.
# config.toml provides configurations for WAF deployment and capabilities.

### Network Configurations

[WebServer]
ip = "127.0.0.1"
port = 50000

[Proxy]
ip = "127.0.0.1"
port = 8080

[Admin]
ip = "127.0.0.1"
port = 60000

### Further sections are related to WAF features.

[ACL]
api = "https://check.torproject.org/exit-addresses"
backup = "C:\\coding\\NetGuard\\src\\proxy_network\\TorExitNodes.txt"
interval = 1800 # 30 minutes

[Timezone]
time_zone = "Asia/Jerusalem"